; Mega 2560+ Firmware
; Two MCUs on one board:
;   - ATmega2560 : main MCU, USB-UART (FT231XS), FM24C64C FRAM on I2C
;   - ESP32-S3   : WiFi/BT co-processor + sensor reading (I2C1 + SPI3)

[env:mega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter = +<mega2560/>

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = +<esp32/>
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
